Textalk/websocket-php

- lib/Base.php
Initialize $payload. As sometimes (with Slack) we get a websocket packet with payload_length == 0 (probably a ping packet or something?) This will break the `return $payload`, as it will not have been initialized.
> Initialize $payload

- lib/Client.php
- tests/unit/ClientTest.php
Some websocket servers (in my case Autobahn) does not accept Host headers that does not include the port if the port is non-standard, and returns an HTTP error : 
`HTTP/1.1 400 missing port in HTTP Host header 'localhost' and server runs on non-standard port 9000`
This patches fixes this error
> Add port in Host request-header during handshake

- .travis.yml
- composer.json
- composer.lock
- lib/Client.php
- lib/Server.php
- tests/bin/ratchetserver.php
- tests/unit/ClientTest.php
The production difference here is that the whole header is read in one PHP function call instead of looping line by line.
Added a ratchet-server in the test suite, since several issues have been using this as a client towards a ratchet server.  Unfortunately, ratchet can't be installed on 5.3, so I had to remove that from the continuous integration on travis.
> Reading full header

- lib/Client.php
- tests/unit/ClientTest.php
Swapped fsockopen to stream_socket_client and added context option in the constructor options. This is a better solution than suggested in #21 since it allows passing in any stream context options without modifying the base code.
> Stream context option support

- .travis.yml
Seems like all the builds on travis are failing due to `Xenial` being the new default.
https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723/5
> .travis.yml - Added dist option to force distro version

- lib/Base.php
- tests/ClientTest.php
- tests/ServerTest.php
- tests/scripts/ping-pong.json
According to [rfc](https://tools.ietf.org/html/rfc6455#section-5.5.3) need to respond with the same data that came in the request.
Currently working incorrectly with ratchet websocket server.
> Fix ping/pong interaction

- lib/Base.php
- tests/ClientTest.php
- tests/ServerTest.php
- tests/scripts/ping-pong.json
According to [rfc](https://tools.ietf.org/html/rfc6455#section-5.5.2) documentation, ping message **may** not include application data.
But pong frame **must** have identical application data as found in ping message.
So, this patch make ability to send empty response pong for empty request ping.
> Fix bug with empty response message

- .travis.yml
- codestandard.xml
- composer.json
- lib/ConnectionException.php
Dropping support for old PHP versions, `5.x ` and `7.0`.
This enables us to replace deprecated dependencies and use more modern PHP code.
Scheduled for `v1.4` release.
> [v1.4] PHP version ^7.1

- lib/Base.php
- lib/TimeoutException.php
- tests/ClientTest.php
Hello,
I'm hoping this change isn't too intrusive but I wanted to introduce a more granular type of connection exception. I have a separate patch coming that introduces persistence as a client connection option and one of the possibilities it introduces is the idea that the re-used connection from a previous request may time out. Some client applications using persistence as an option may want to easily catch a timeout and attempt to re-connect.
Thanks,
Michael
> Introduce TimeoutException as a type of ConnectionException

- README.md
- lib/Base.php
- lib/Client.php
- tests/ClientTest.php
- tests/scripts/client.connect-persistent.json
- tests/scripts/send-broken-write.json
- tests/scripts/send-failed-write.json
Hello,
I'd like to propose adding a "persistent" boolean option to the list of available options for a websocket client. When this option is used, it's possible for a connection from a previous request to timeout. It's suggested that if "fwrite" returns false, that "fclose" needs to be called for the resource to be let go. https://www.php.net/manual/en/function.pfsockopen.php#108929
Regards,
Michael
> Adding persistent connection option.

- lib/Base.php
- tests/scripts/client.connect-persistent.json
- tests/scripts/client.reconnect.json
A friend of mine made the original change for supporting persistent connections, but it seems to have an issue.
When you set the persistent flag on a socket stream, php changes the resource type from "stream" to "persistent stream". This causes the isConnected() function on Websocket\Base to erroneously assume that the resource type is invalid, preventing us from resolving the connect function.
I've updated the isConnected() function to account for this issue and updated tests accordingly.
> fix bug in isConnected function when evaluating persistent connections

- lib/Base.php
- tests/ClientTest.php
- tests/ServerTest.php
- tests/scripts/ping-pong.json
Messages of type `ping` and `pong` are completely handled internally, and never returned to calling code. This behavior ensures that fragmented messages don't break when a control message occurs between fragments.
Replaces PR https://github.com/Textalk/websocket-php/pull/87
> Ping & Pong, handle internally, continue reading

- .gitignore
- .travis.yml
- README.md
- composer.json
- docs/COPYING.md
- docs/Changelog.md
- docs/Client.md
- docs/Contributing.md
- docs/Server.md
- lib/Base.php
- lib/Client.php
- lib/Server.php
- tests/mock/MockSocket.php
* Setting minimum php version to `7.2`
* Splitting documentation into separate files in `docs` directory
* Type hint method returns
* Consistent `array` notation
> Php 7.2 & Documentation

- lib/Client.php
Line breaks are applied later. Current code added an extra line break on `authorization` header.
Closing https://github.com/Textalk/websocket-php/issues/107
> Header line break fix

- docs/Changelog.md
- docs/Client.md
- docs/Server.md
- lib/Base.php
- lib/Client.php
- lib/Server.php
- tests/ClientTest.php
- tests/ServerTest.php
- tests/scripts/receive-fragmentation.json
Re-writing the receive() method.
Better handling of interrupted fragmented messages. That is, when a control frame is received content frames in a fragmented messages. Handled by using an internal buffer.
Ability to specify which opcodes to return. Default is `text` and `binary`, but by specifying the filter other opcodes may be returned as well.
Method getLastOpcode() by default returns opcode of last returned message. With argument `true` it will instead return opcode of last read frame, regardless if it was returned or not.
> Receiver rewrite

- docs/Changelog.md
- lib/Base.php
- tests/scripts/receive-broken-read.json
- tests/scripts/receive-empty-read.json
Ensure failed read operations also close stream. If not, the stream might appear usable and not automatically reconnect as expected. We already do this on write operations.
> Read fixes

- docs/Client.md
- docs/Server.md
- lib/Base.php
- tests/ClientTest.php
- tests/ServerTest.php
- tests/mock/MockSocket.php
- tests/scripts/send-convenicance.json
* getName() - local socket name  - e.g. `127.0.0.1:8000 `
* getRemoteName() - remote socket name - e.g. `127.0.0.1:12345 `
* __toString() - string representation of instance - e.g. `WebSocket\Server(127.0.0.1:8000)`
> Name methods

- .travis.yml
- Makefile
- docs/Changelog.md
- examples/echoserver.php
- lib/Base.php
- lib/Client.php
- lib/Server.php
- tests/scripts/receive-broken-read.json
- tests/scripts/receive-empty-read.json
- tests/scripts/send-broken-write.json
- tests/scripts/send-failed-write.json
* Solve stream closure/get meta conflict
* Examples and documentation overhaul
> Version 1.4.3

- README.md
> Fix typo (wrong URL) in Readme.MD

- lib/Base.php
- lib/Client.php
- tests/ClientTest.php
- tests/mock/mock-socket.php
- tests/scripts/client.connect-persistent.json
- tests/scripts/client.destruct.json
I thought I had fixed persistent connections with my last commit, but I did not. I've now robustly tested that this does indeed result in connections persisting across multiple php requests (Make sure you have php-fpm configured as "pm = static").
In this change I've silenced errors on fwrite/fread, which will fail before you realize you aren't "connected", resulting in an error bubbling up to the client. This means that our logic must always account for the possible need to retry.
The usage pattern for persistent connections then looks something like this:
class PersistentWebsocket {
private $client = null;
public function __construct($url, $timeout) {
$this->client = new WebSocket\Client(
$url,
[
'timeout'    => $timeout,
'persistent' => true,
]
);
}
public function send($request, …
> Persistent connections still not working as intended. This fixes them.

- lib/Base.php
Second argument required.
Closing #130
> Fix for stream_socket_get_name

- lib/Base.php
This improves performance massively (~7x) in case the data
gets send without masking.
> Don't append payload per byte unless necessary

- lib/Client.php
Variable `$address` is used outside the if-block, so moving the setting if it outside as well.
> Fix for persistent connection in client

- lib/Base.php
- tests/ClientTest.php
- tests/scripts/receive-client-timeout.json
- tests/scripts/receive-empty-read.json
PR to solve issue #139 
When a timeout occurs on the client-side in the `$client->receive()` call this throws a TimeoutException earlier and keeps the connection open. This allows a PING to be sent to keep the connection alive if needed by the server.
> Throw client read timeout earlier and don’t close connection

- lib/Client.php
- tests/ClientTest.php
- tests/mock/MockSocket.php
- tests/scripts/client.connect-root.json
- tests/scripts/client.connect.json
Fulfilling expectations for HTTP request target
* Path must be absolute (i.e. beginning with `/`)
* Fragment should not be included, only path and query
* Improved testing of generated headers
Extends https://github.com/Textalk/websocket-php/pull/165
> Fix client path for http request
